export const data = [
  {
    Handle: "bangle-bracelet",
    Title: "Bangle Bracelet",
    "Body (HTML)": "<p>Gold bangle bracelet with studded jewels.</p>",
    Vendor: "Company 123",
    "Product Category": "",
    Type: "Bracelet",
    Tags: "Diamond, Gem, Gold",
    Published: true,
    "Option1 Name": "Title",
    "Option1 Value": "Default Title",
    "Option2 Name": "",
    "Option2 Value": "",
    "Option3 Name": "",
    "Option3 Value": "",
    "Variant SKU": "",
    "Variant Grams": 0,
    "Variant Inventory Tracker": "",
    "Variant Inventory Qty": 1,
    "Variant Inventory Policy": "deny",
    "Variant Fulfillment Service": "manual",
    "Variant Price": 39.99,
    "Variant Compare At Price": 43.99,
    "Variant Requires Shipping": true,
    "Variant Taxable": true,
    "Variant Barcode": "",
    "Image Src":
      "https://cdn.shopify.com/s/files/1/0814/6190/3638/products/bangle-bracelet-with-jewels_925x_f845a6d3-7610-43f5-93cd-4637da39a6ea.jpg?v=1692687702",
    "Image Position": 1,
    "Image Alt Text": "",
    "Gift Card": false,
    "SEO Title": "",
    "SEO Description": "",
    "Google Shopping / Google Product Category": "",
    "Google Shopping / Gender": "",
    "Google Shopping / Age Group": "",
    "Google Shopping / MPN": "",
    "Google Shopping / Condition": "",
    "Google Shopping / Custom Product": "",
    "Google Shopping / Custom Label 0": "",
    "Google Shopping / Custom Label 1": "",
    "Google Shopping / Custom Label 2": "",
    "Google Shopping / Custom Label 3": "",
    "Google Shopping / Custom Label 4": "",
    "Variant Image": "",
    "Variant Weight Unit": "kg",
    "Variant Tax Code": "",
    "Cost per item": "",
    "Included / India": true,
    "Included / International": true,
    "Price / International": "",
    "Compare At Price / International": "",
    Status: "active",
  },
  {
    Handle: "bangle-bracelet-with-feathers",
    Title: "Boho Bangle Bracelet",
    "Body (HTML)": "<p>Gold boho bangle bracelet with multicolor tassels.</p>",
    Vendor: "Company 123",
    "Product Category": "",
    Type: "Bracelet",
    Tags: "Gold",
    Published: true,
    "Option1 Name": "Title",
    "Option1 Value": "Default Title",
    "Option2 Name": "",
    "Option2 Value": "",
    "Option3 Name": "",
    "Option3 Value": "",
    "Variant SKU": "",
    "Variant Grams": 0,
    "Variant Inventory Tracker": "",
    "Variant Inventory Qty": 1,
    "Variant Inventory Policy": "deny",
    "Variant Fulfillment Service": "manual",
    "Variant Price": 42.99,
    "Variant Compare At Price": 44.99,
    "Variant Requires Shipping": true,
    "Variant Taxable": true,
    "Variant Barcode": "",
    "Image Src":
      "https://cdn.shopify.com/s/files/1/0814/6190/3638/products/bangle-bracelet-with-feathers_925x_402582d7-4fe1-4a29-ba6d-a0b3474ec536.jpg?v=1692687703",
    "Image Position": 1,
    "Image Alt Text": "",
    "Gift Card": false,
    "SEO Title": "",
    "SEO Description": "",
    "Google Shopping / Google Product Category": "",
    "Google Shopping / Gender": "",
    "Google Shopping / Age Group": "",
    "Google Shopping / MPN": "",
    "Google Shopping / Condition": "",
    "Google Shopping / Custom Product": "",
    "Google Shopping / Custom Label 0": "",
    "Google Shopping / Custom Label 1": "",
    "Google Shopping / Custom Label 2": "",
    "Google Shopping / Custom Label 3": "",
    "Google Shopping / Custom Label 4": "",
    "Variant Image": "",
    "Variant Weight Unit": "kg",
    "Variant Tax Code": "",
    "Cost per item": "",
    "Included / India": true,
    "Included / International": true,
    "Price / International": "",
    "Compare At Price / International": "",
    Status: "active",
  },
  {
    Handle: "boho-earrings",
    Title: "Boho Earrings",
    "Body (HTML)": "<p>Turquoise globe earrings on 14k gold hooks.</p>",
    Vendor: "Company 123",
    "Product Category": "",
    Type: "Earrings",
    Tags: "Silver, Turquoise",
    Published: false,
    "Option1 Name": "Title",
    "Option1 Value": "Default Title",
    "Option2 Name": "",
    "Option2 Value": "",
    "Option3 Name": "",
    "Option3 Value": "",
    "Variant SKU": "",
    "Variant Grams": 28.0008239905625,
    "Variant Inventory Tracker": "",
    "Variant Inventory Qty": 1,
    "Variant Inventory Policy": "deny",
    "Variant Fulfillment Service": "manual",
    "Variant Price": 27.99,
    "Variant Compare At Price": 35.99,
    "Variant Requires Shipping": true,
    "Variant Taxable": true,
    "Variant Barcode": "",
    "Image Src":
      "https://cdn.shopify.com/s/files/1/0814/6190/3638/products/boho-earrings_925x_78083696-bfa7-4bfa-8f30-1e84d5624203.jpg?v=1692687706",
    "Image Position": 1,
    "Image Alt Text": "",
    "Gift Card": false,
    "SEO Title": "",
    "SEO Description": "",
    "Google Shopping / Google Product Category": "",
    "Google Shopping / Gender": "",
    "Google Shopping / Age Group": "",
    "Google Shopping / MPN": "",
    "Google Shopping / Condition": "",
    "Google Shopping / Custom Product": "",
    "Google Shopping / Custom Label 0": "",
    "Google Shopping / Custom Label 1": "",
    "Google Shopping / Custom Label 2": "",
    "Google Shopping / Custom Label 3": "",
    "Google Shopping / Custom Label 4": "",
    "Variant Image": "",
    "Variant Weight Unit": "oz",
    "Variant Tax Code": "",
    "Cost per item": "",
    "Included / India": true,
    "Included / International": true,
    "Price / International": "",
    "Compare At Price / International": "",
    Status: "draft",
  },
  {
    Handle: "boho-earrings",
    Title: "",
    "Body (HTML)": "",
    Vendor: "",
    "Product Category": "",
    Type: "",
    Tags: "",
    Published: "",
    "Option1 Name": "",
    "Option1 Value": "",
    "Option2 Name": "",
    "Option2 Value": "",
    "Option3 Name": "",
    "Option3 Value": "",
    "Variant SKU": "",
    "Variant Grams": "",
    "Variant Inventory Tracker": "",
    "Variant Inventory Qty": "",
    "Variant Inventory Policy": "",
    "Variant Fulfillment Service": "",
    "Variant Price": "",
    "Variant Compare At Price": "",
    "Variant Requires Shipping": "",
    "Variant Taxable": "",
    "Variant Barcode": "",
    "Image Src":
      "https://cdn.shopify.com/s/files/1/0814/6190/3638/products/inspired-woman_925x_ee214cab-ce69-4ea7-9f04-49356c0e1ce2.jpg?v=1692687706",
    "Image Position": 2,
    "Image Alt Text": "",
    "Gift Card": "",
    "SEO Title": "",
    "SEO Description": "",
    "Google Shopping / Google Product Category": "",
    "Google Shopping / Gender": "",
    "Google Shopping / Age Group": "",
    "Google Shopping / MPN": "",
    "Google Shopping / Condition": "",
    "Google Shopping / Custom Product": "",
    "Google Shopping / Custom Label 0": "",
    "Google Shopping / Custom Label 1": "",
    "Google Shopping / Custom Label 2": "",
    "Google Shopping / Custom Label 3": "",
    "Google Shopping / Custom Label 4": "",
    "Variant Image": "",
    "Variant Weight Unit": "",
    "Variant Tax Code": "",
    "Cost per item": "",
    "Included / India": "",
    "Included / International": "",
    "Price / International": "",
    "Compare At Price / International": "",
    Status: "",
  },
  {
    Handle: "boho-earrings",
    Title: "",
    "Body (HTML)": "",
    Vendor: "",
    "Product Category": "",
    Type: "",
    Tags: "",
    Published: "",
    "Option1 Name": "",
    "Option1 Value": "",
    "Option2 Name": "",
    "Option2 Value": "",
    "Option3 Name": "",
    "Option3 Value": "",
    "Variant SKU": "",
    "Variant Grams": "",
    "Variant Inventory Tracker": "",
    "Variant Inventory Qty": "",
    "Variant Inventory Policy": "",
    "Variant Fulfillment Service": "",
    "Variant Price": "",
    "Variant Compare At Price": "",
    "Variant Requires Shipping": "",
    "Variant Taxable": "",
    "Variant Barcode": "",
    "Image Src":
      "https://cdn.shopify.com/s/files/1/0814/6190/3638/products/necklace-earrings-set_925x_ac7d081d-22d9-4be3-859b-2baf140cf510.jpg?v=1692687706",
    "Image Position": 3,
    "Image Alt Text": "",
    "Gift Card": "",
    "SEO Title": "",
    "SEO Description": "",
    "Google Shopping / Google Product Category": "",
    "Google Shopping / Gender": "",
    "Google Shopping / Age Group": "",
    "Google Shopping / MPN": "",
    "Google Shopping / Condition": "",
    "Google Shopping / Custom Product": "",
    "Google Shopping / Custom Label 0": "",
    "Google Shopping / Custom Label 1": "",
    "Google Shopping / Custom Label 2": "",
    "Google Shopping / Custom Label 3": "",
    "Google Shopping / Custom Label 4": "",
    "Variant Image": "",
    "Variant Weight Unit": "",
    "Variant Tax Code": "",
    "Cost per item": "",
    "Included / India": "",
    "Included / International": "",
    "Price / International": "",
    "Compare At Price / International": "",
    Status: "",
  },
  {
    Handle: "chain-bracelet",
    Title: "7 Shakra Bracelet",
    "Body (HTML)": "<p>7 chakra bracelet, in blue or black.</p>",
    Vendor: "Company 123",
    "Product Category": "",
    Type: "Bracelet",
    Tags: "Beads",
    Published: true,
    "Option1 Name": "Color",
    "Option1 Value": "Blue",
    "Option2 Name": "",
    "Option2 Value": "",
    "Option3 Name": "",
    "Option3 Value": "",
    "Variant SKU": "",
    "Variant Grams": 0,
    "Variant Inventory Tracker": "",
    "Variant Inventory Qty": 1,
    "Variant Inventory Policy": "deny",
    "Variant Fulfillment Service": "manual",
    "Variant Price": 42.99,
    "Variant Compare At Price": 44.99,
    "Variant Requires Shipping": true,
    "Variant Taxable": true,
    "Variant Barcode": "",
    "Image Src":
      "https://cdn.shopify.com/s/files/1/0814/6190/3638/products/7-chakra-bracelet_925x_bde213f9-f707-418a-a603-67988c20959e.jpg?v=1692687696",
    "Image Position": 1,
    "Image Alt Text": "",
    "Gift Card": false,
    "SEO Title": "",
    "SEO Description": "",
    "Google Shopping / Google Product Category": "",
    "Google Shopping / Gender": "",
    "Google Shopping / Age Group": "",
    "Google Shopping / MPN": "",
    "Google Shopping / Condition": "",
    "Google Shopping / Custom Product": "",
    "Google Shopping / Custom Label 0": "",
    "Google Shopping / Custom Label 1": "",
    "Google Shopping / Custom Label 2": "",
    "Google Shopping / Custom Label 3": "",
    "Google Shopping / Custom Label 4": "",
    "Variant Image":
      "https://cdn.shopify.com/s/files/1/0814/6190/3638/products/navy-blue-chakra-bracelet_925x_fe53db6d-8125-4c55-b890-a79c6e80dc44.jpg?v=1692687696",
    "Variant Weight Unit": "kg",
    "Variant Tax Code": "",
    "Cost per item": "",
    "Included / India": true,
    "Included / International": true,
    "Price / International": "",
    "Compare At Price / International": "",
    Status: "active",
  },
  {
    Handle: "chain-bracelet",
    Title: "",
    "Body (HTML)": "",
    Vendor: "",
    "Product Category": "",
    Type: "",
    Tags: "",
    Published: "",
    "Option1 Name": "",
    "Option1 Value": "Black",
    "Option2 Name": "",
    "Option2 Value": "",
    "Option3 Name": "",
    "Option3 Value": "",
    "Variant SKU": "",
    "Variant Grams": 0,
    "Variant Inventory Tracker": "",
    "Variant Inventory Qty": 0,
    "Variant Inventory Policy": "deny",
    "Variant Fulfillment Service": "manual",
    "Variant Price": 42.99,
    "Variant Compare At Price": 44.99,
    "Variant Requires Shipping": true,
    "Variant Taxable": true,
    "Variant Barcode": "",
    "Image Src":
      "https://cdn.shopify.com/s/files/1/0814/6190/3638/products/navy-blue-chakra-bracelet_925x_fe53db6d-8125-4c55-b890-a79c6e80dc44.jpg?v=1692687696",
    "Image Position": 2,
    "Image Alt Text": "",
    "Gift Card": "",
    "SEO Title": "",
    "SEO Description": "",
    "Google Shopping / Google Product Category": "",
    "Google Shopping / Gender": "",
    "Google Shopping / Age Group": "",
    "Google Shopping / MPN": "",
    "Google Shopping / Condition": "",
    "Google Shopping / Custom Product": "",
    "Google Shopping / Custom Label 0": "",
    "Google Shopping / Custom Label 1": "",
    "Google Shopping / Custom Label 2": "",
    "Google Shopping / Custom Label 3": "",
    "Google Shopping / Custom Label 4": "",
    "Variant Image":
      "https://cdn.shopify.com/s/files/1/0814/6190/3638/products/7-chakra-bracelet_925x_bde213f9-f707-418a-a603-67988c20959e.jpg?v=1692687696",
    "Variant Weight Unit": "kg",
    "Variant Tax Code": "",
    "Cost per item": "",
    "Included / India": "",
    "Included / International": "",
    "Price / International": "",
    "Compare At Price / International": "",
    Status: "",
  },
  {
    Handle: "choker-with-bead",
    Title: "Choker with Bead",
    "Body (HTML)": "<p>Black choker necklace with 14k gold bead.</p>",
    Vendor: "Company 123",
    "Product Category": "",
    Type: "Necklace",
    Tags: "Gold, Leather",
    Published: true,
    "Option1 Name": "Title",
    "Option1 Value": "Default Title",
    "Option2 Name": "",
    "Option2 Value": "",
    "Option3 Name": "",
    "Option3 Value": "",
    "Variant SKU": "",
    "Variant Grams": 0,
    "Variant Inventory Tracker": "",
    "Variant Inventory Qty": 1,
    "Variant Inventory Policy": "deny",
    "Variant Fulfillment Service": "manual",
    "Variant Price": 14.99,
    "Variant Compare At Price": 19.99,
    "Variant Requires Shipping": true,
    "Variant Taxable": true,
    "Variant Barcode": "",
    "Image Src":
      "https://cdn.shopify.com/s/files/1/0814/6190/3638/products/black-choker-with-bead_925x_fad63abe-7c3b-41b1-b1ce-cd20baef85e2.jpg?v=1692687709",
    "Image Position": 1,
    "Image Alt Text": "",
    "Gift Card": false,
    "SEO Title": "",
    "SEO Description": "",
    "Google Shopping / Google Product Category": "",
    "Google Shopping / Gender": "",
    "Google Shopping / Age Group": "",
    "Google Shopping / MPN": "",
    "Google Shopping / Condition": "",
    "Google Shopping / Custom Product": "",
    "Google Shopping / Custom Label 0": "",
    "Google Shopping / Custom Label 1": "",
    "Google Shopping / Custom Label 2": "",
    "Google Shopping / Custom Label 3": "",
    "Google Shopping / Custom Label 4": "",
    "Variant Image": "",
    "Variant Weight Unit": "kg",
    "Variant Tax Code": "",
    "Cost per item": "",
    "Included / India": true,
    "Included / International": true,
    "Price / International": "",
    "Compare At Price / International": "",
    Status: "active",
  },
  {
    Handle: "choker-with-bead",
    Title: "",
    "Body (HTML)": "",
    Vendor: "",
    "Product Category": "",
    Type: "",
    Tags: "",
    Published: "",
    "Option1 Name": "",
    "Option1 Value": "",
    "Option2 Name": "",
    "Option2 Value": "",
    "Option3 Name": "",
    "Option3 Value": "",
    "Variant SKU": "",
    "Variant Grams": "",
    "Variant Inventory Tracker": "",
    "Variant Inventory Qty": "",
    "Variant Inventory Policy": "",
    "Variant Fulfillment Service": "",
    "Variant Price": "",
    "Variant Compare At Price": "",
    "Variant Requires Shipping": "",
    "Variant Taxable": "",
    "Variant Barcode": "",
    "Image Src":
      "https://cdn.shopify.com/s/files/1/0814/6190/3638/products/choker-with-bead_925x_68ae0f59-65d1-415c-af2c-098f075d37b8.jpg?v=1692687709",
    "Image Position": 2,
    "Image Alt Text": "",
    "Gift Card": "",
    "SEO Title": "",
    "SEO Description": "",
    "Google Shopping / Google Product Category": "",
    "Google Shopping / Gender": "",
    "Google Shopping / Age Group": "",
    "Google Shopping / MPN": "",
    "Google Shopping / Condition": "",
    "Google Shopping / Custom Product": "",
    "Google Shopping / Custom Label 0": "",
    "Google Shopping / Custom Label 1": "",
    "Google Shopping / Custom Label 2": "",
    "Google Shopping / Custom Label 3": "",
    "Google Shopping / Custom Label 4": "",
    "Variant Image": "",
    "Variant Weight Unit": "",
    "Variant Tax Code": "",
    "Cost per item": "",
    "Included / India": "",
    "Included / International": "",
    "Price / International": "",
    "Compare At Price / International": "",
    Status: "",
  },
  {
    Handle: "choker-with-gold-pendant",
    Title: "Choker with Gold Pendant",
    "Body (HTML)":
      'Black cord choker with gold pendant. Beautifully died black leather shapes a choker necklace with findings of 14k yellow gold, displaying gold pendant in a gorgeous balance of dark and light, delicate and strong.<ul>\n<li>14k yellow gold</li>\n<li>Leather</li>\n<li>Length, 12" with 2.5" extender</li>\n<li>Width, 0.3"</li>\n<li>Lobster clasp</li>\n<li>Made in USA</li>\n</ul>',
    Vendor: "Company 123",
    "Product Category": "",
    Type: "Necklace",
    Tags: "Choker, Gold, Leather, Pendant",
    Published: true,
    "Option1 Name": "Title",
    "Option1 Value": "Default Title",
    "Option2 Name": "",
    "Option2 Value": "",
    "Option3 Name": "",
    "Option3 Value": "",
    "Variant SKU": "",
    "Variant Grams": 0,
    "Variant Inventory Tracker": "",
    "Variant Inventory Qty": 1,
    "Variant Inventory Policy": "deny",
    "Variant Fulfillment Service": "manual",
    "Variant Price": 29.99,
    "Variant Compare At Price": "",
    "Variant Requires Shipping": true,
    "Variant Taxable": true,
    "Variant Barcode": "",
    "Image Src":
      "https://cdn.shopify.com/s/files/1/0814/6190/3638/products/choker-with-gold-pendant_925x_a4f90507-3d7d-4b7a-9cd0-68b478bd1380.jpg?v=1692687712",
    "Image Position": 1,
    "Image Alt Text": "",
    "Gift Card": false,
    "SEO Title": "",
    "SEO Description": "",
    "Google Shopping / Google Product Category": "",
    "Google Shopping / Gender": "",
    "Google Shopping / Age Group": "",
    "Google Shopping / MPN": "",
    "Google Shopping / Condition": "",
    "Google Shopping / Custom Product": "",
    "Google Shopping / Custom Label 0": "",
    "Google Shopping / Custom Label 1": "",
    "Google Shopping / Custom Label 2": "",
    "Google Shopping / Custom Label 3": "",
    "Google Shopping / Custom Label 4": "",
    "Variant Image": "",
    "Variant Weight Unit": "kg",
    "Variant Tax Code": "",
    "Cost per item": "",
    "Included / India": true,
    "Included / International": true,
    "Price / International": "",
    "Compare At Price / International": "",
    Status: "active",
  },
  {
    Handle: "choker-with-gold-pendant",
    Title: "",
    "Body (HTML)": "",
    Vendor: "",
    "Product Category": "",
    Type: "",
    Tags: "",
    Published: "",
    "Option1 Name": "",
    "Option1 Value": "",
    "Option2 Name": "",
    "Option2 Value": "",
    "Option3 Name": "",
    "Option3 Value": "",
    "Variant SKU": "",
    "Variant Grams": "",
    "Variant Inventory Tracker": "",
    "Variant Inventory Qty": "",
    "Variant Inventory Policy": "",
    "Variant Fulfillment Service": "",
    "Variant Price": "",
    "Variant Compare At Price": "",
    "Variant Requires Shipping": "",
    "Variant Taxable": "",
    "Variant Barcode": "",
    "Image Src":
      "https://cdn.shopify.com/s/files/1/0814/6190/3638/products/choker-pendant-closeup_925x_396c2c73-b2af-4d3b-8230-f3e9e3043971.jpg?v=1692687712",
    "Image Position": 2,
    "Image Alt Text": "",
    "Gift Card": "",
    "SEO Title": "",
    "SEO Description": "",
    "Google Shopping / Google Product Category": "",
    "Google Shopping / Gender": "",
    "Google Shopping / Age Group": "",
    "Google Shopping / MPN": "",
    "Google Shopping / Condition": "",
    "Google Shopping / Custom Product": "",
    "Google Shopping / Custom Label 0": "",
    "Google Shopping / Custom Label 1": "",
    "Google Shopping / Custom Label 2": "",
    "Google Shopping / Custom Label 3": "",
    "Google Shopping / Custom Label 4": "",
    "Variant Image": "",
    "Variant Weight Unit": "",
    "Variant Tax Code": "",
    "Cost per item": "",
    "Included / India": "",
    "Included / International": "",
    "Price / International": "",
    "Compare At Price / International": "",
    Status: "",
  },
  {
    Handle: "choker-with-triangle",
    Title: "Choker with Triangle",
    "Body (HTML)": "<p>Black choker with silver triangle pendant.</p>",
    Vendor: "Company 123",
    "Product Category": "",
    Type: "Necklace",
    Tags: "Leather, Silver, Triangle",
    Published: true,
    "Option1 Name": "Title",
    "Option1 Value": "Default Title",
    "Option2 Name": "",
    "Option2 Value": "",
    "Option3 Name": "",
    "Option3 Value": "",
    "Variant SKU": "",
    "Variant Grams": 0,
    "Variant Inventory Tracker": "",
    "Variant Inventory Qty": 1,
    "Variant Inventory Policy": "deny",
    "Variant Fulfillment Service": "manual",
    "Variant Price": 47.99,
    "Variant Compare At Price": 49.99,
    "Variant Requires Shipping": true,
    "Variant Taxable": true,
    "Variant Barcode": "",
    "Image Src":
      "https://cdn.shopify.com/s/files/1/0814/6190/3638/products/choker-with-triangle_925x_010527c5-bcd4-4f32-a89d-f954cdfc8373.jpg?v=1692687713",
    "Image Position": 1,
    "Image Alt Text": "",
    "Gift Card": false,
    "SEO Title": "",
    "SEO Description": "",
    "Google Shopping / Google Product Category": "",
    "Google Shopping / Gender": "",
    "Google Shopping / Age Group": "",
    "Google Shopping / MPN": "",
    "Google Shopping / Condition": "",
    "Google Shopping / Custom Product": "",
    "Google Shopping / Custom Label 0": "",
    "Google Shopping / Custom Label 1": "",
    "Google Shopping / Custom Label 2": "",
    "Google Shopping / Custom Label 3": "",
    "Google Shopping / Custom Label 4": "",
    "Variant Image": "",
    "Variant Weight Unit": "kg",
    "Variant Tax Code": "",
    "Cost per item": "",
    "Included / India": true,
    "Included / International": true,
    "Price / International": "",
    "Compare At Price / International": "",
    Status: "active",
  },
  {
    Handle: "dainty-gold-neclace",
    Title: "Dainty Gold Necklace",
    "Body (HTML)": "<p>Dainty gold necklace with two pendants.</p>",
    Vendor: "Company 123",
    "Product Category": "",
    Type: "Necklace",
    Tags: "Gold, Pendant",
    Published: true,
    "Option1 Name": "Title",
    "Option1 Value": "Default Title",
    "Option2 Name": "",
    "Option2 Value": "",
    "Option3 Name": "",
    "Option3 Value": "",
    "Variant SKU": "",
    "Variant Grams": 0,
    "Variant Inventory Tracker": "",
    "Variant Inventory Qty": 1,
    "Variant Inventory Policy": "deny",
    "Variant Fulfillment Service": "manual",
    "Variant Price": 63.99,
    "Variant Compare At Price": 69.99,
    "Variant Requires Shipping": true,
    "Variant Taxable": true,
    "Variant Barcode": "",
    "Image Src":
      "https://cdn.shopify.com/s/files/1/0814/6190/3638/products/dainty-gold-necklace_925x_69d8ab12-6bfe-4f7a-b2a5-ef2bbee77c2b.jpg?v=1692687716",
    "Image Position": 1,
    "Image Alt Text": "",
    "Gift Card": false,
    "SEO Title": "",
    "SEO Description": "",
    "Google Shopping / Google Product Category": "",
    "Google Shopping / Gender": "",
    "Google Shopping / Age Group": "",
    "Google Shopping / MPN": "",
    "Google Shopping / Condition": "",
    "Google Shopping / Custom Product": "",
    "Google Shopping / Custom Label 0": "",
    "Google Shopping / Custom Label 1": "",
    "Google Shopping / Custom Label 2": "",
    "Google Shopping / Custom Label 3": "",
    "Google Shopping / Custom Label 4": "",
    "Variant Image": "",
    "Variant Weight Unit": "kg",
    "Variant Tax Code": "",
    "Cost per item": "",
    "Included / India": true,
    "Included / International": true,
    "Price / International": "",
    "Compare At Price / International": "",
    Status: "active",
  },
  {
    Handle: "dainty-gold-neclace",
    Title: "",
    "Body (HTML)": "",
    Vendor: "",
    "Product Category": "",
    Type: "",
    Tags: "",
    Published: "",
    "Option1 Name": "",
    "Option1 Value": "",
    "Option2 Name": "",
    "Option2 Value": "",
    "Option3 Name": "",
    "Option3 Value": "",
    "Variant SKU": "",
    "Variant Grams": "",
    "Variant Inventory Tracker": "",
    "Variant Inventory Qty": "",
    "Variant Inventory Policy": "",
    "Variant Fulfillment Service": "",
    "Variant Price": "",
    "Variant Compare At Price": "",
    "Variant Requires Shipping": "",
    "Variant Taxable": "",
    "Variant Barcode": "",
    "Image Src":
      "https://cdn.shopify.com/s/files/1/0814/6190/3638/products/womens-gold-necklace_925x_34067ade-14e7-4f16-b9c6-7afee8acfcbe.jpg?v=1692687716",
    "Image Position": 2,
    "Image Alt Text": "",
    "Gift Card": "",
    "SEO Title": "",
    "SEO Description": "",
    "Google Shopping / Google Product Category": "",
    "Google Shopping / Gender": "",
    "Google Shopping / Age Group": "",
    "Google Shopping / MPN": "",
    "Google Shopping / Condition": "",
    "Google Shopping / Custom Product": "",
    "Google Shopping / Custom Label 0": "",
    "Google Shopping / Custom Label 1": "",
    "Google Shopping / Custom Label 2": "",
    "Google Shopping / Custom Label 3": "",
    "Google Shopping / Custom Label 4": "",
    "Variant Image": "",
    "Variant Weight Unit": "",
    "Variant Tax Code": "",
    "Cost per item": "",
    "Included / India": "",
    "Included / International": "",
    "Price / International": "",
    "Compare At Price / International": "",
    Status: "",
  },
  {
    Handle: "dreamcatcher-pendant-necklace",
    Title: "Dreamcatcher Pendant Necklace",
    "Body (HTML)":
      "<p>Turquoise beaded dream catcher necklace. Silver feathers adorn this beautiful dream catcher, which move and twinkle as you walk.</p>",
    Vendor: "Sterling Ltd",
    "Product Category": "",
    Type: "Necklace",
    Tags: "Dreamcatcher, Pendant, Silver, Turquoise",
    Published: true,
    "Option1 Name": "Title",
    "Option1 Value": "Default Title",
    "Option2 Name": "",
    "Option2 Value": "",
    "Option3 Name": "",
    "Option3 Value": "",
    "Variant SKU": "",
    "Variant Grams": 0,
    "Variant Inventory Tracker": "",
    "Variant Inventory Qty": 1,
    "Variant Inventory Policy": "deny",
    "Variant Fulfillment Service": "manual",
    "Variant Price": 23.99,
    "Variant Compare At Price": 41.99,
    "Variant Requires Shipping": true,
    "Variant Taxable": true,
    "Variant Barcode": "",
    "Image Src":
      "https://cdn.shopify.com/s/files/1/0814/6190/3638/products/dreamcatcher-pendant-necklace_925x_e8b98ab1-7055-4115-93df-c080f3936c3f.jpg?v=1692687718",
    "Image Position": 1,
    "Image Alt Text": "",
    "Gift Card": false,
    "SEO Title": "",
    "SEO Description": "",
    "Google Shopping / Google Product Category": "",
    "Google Shopping / Gender": "",
    "Google Shopping / Age Group": "",
    "Google Shopping / MPN": "",
    "Google Shopping / Condition": "",
    "Google Shopping / Custom Product": "",
    "Google Shopping / Custom Label 0": "",
    "Google Shopping / Custom Label 1": "",
    "Google Shopping / Custom Label 2": "",
    "Google Shopping / Custom Label 3": "",
    "Google Shopping / Custom Label 4": "",
    "Variant Image": "",
    "Variant Weight Unit": "kg",
    "Variant Tax Code": "",
    "Cost per item": "",
    "Included / India": true,
    "Included / International": true,
    "Price / International": "",
    "Compare At Price / International": "",
    Status: "active",
  },
  {
    Handle: "dreamcatcher-pendant-necklace",
    Title: "",
    "Body (HTML)": "",
    Vendor: "",
    "Product Category": "",
    Type: "",
    Tags: "",
    Published: "",
    "Option1 Name": "",
    "Option1 Value": "",
    "Option2 Name": "",
    "Option2 Value": "",
    "Option3 Name": "",
    "Option3 Value": "",
    "Variant SKU": "",
    "Variant Grams": "",
    "Variant Inventory Tracker": "",
    "Variant Inventory Qty": "",
    "Variant Inventory Policy": "",
    "Variant Fulfillment Service": "",
    "Variant Price": "",
    "Variant Compare At Price": "",
    "Variant Requires Shipping": "",
    "Variant Taxable": "",
    "Variant Barcode": "",
    "Image Src":
      "https://cdn.shopify.com/s/files/1/0814/6190/3638/products/gold-dream-catcher-necklace_925x_61fb2e2a-638f-4936-8719-90c80c35c099.jpg?v=1692687718",
    "Image Position": 2,
    "Image Alt Text": "",
    "Gift Card": "",
    "SEO Title": "",
    "SEO Description": "",
    "Google Shopping / Google Product Category": "",
    "Google Shopping / Gender": "",
    "Google Shopping / Age Group": "",
    "Google Shopping / MPN": "",
    "Google Shopping / Condition": "",
    "Google Shopping / Custom Product": "",
    "Google Shopping / Custom Label 0": "",
    "Google Shopping / Custom Label 1": "",
    "Google Shopping / Custom Label 2": "",
    "Google Shopping / Custom Label 3": "",
    "Google Shopping / Custom Label 4": "",
    "Variant Image": "",
    "Variant Weight Unit": "",
    "Variant Tax Code": "",
    "Cost per item": "",
    "Included / India": "",
    "Included / International": "",
    "Price / International": "",
    "Compare At Price / International": "",
    Status: "",
  },
  {
    Handle: "galaxy-earrings",
    Title: "Galaxy Earrings",
    "Body (HTML)":
      "<p>One set of galaxy earrings, with sterling silver clasps.</p>",
    Vendor: "Sterling Ltd",
    "Product Category": "",
    Type: "Earrings",
    Tags: "Blue, Galaxy, Silver",
    Published: true,
    "Option1 Name": "Title",
    "Option1 Value": "Default Title",
    "Option2 Name": "",
    "Option2 Value": "",
    "Option3 Name": "",
    "Option3 Value": "",
    "Variant SKU": "",
    "Variant Grams": 0,
    "Variant Inventory Tracker": "",
    "Variant Inventory Qty": 1,
    "Variant Inventory Policy": "deny",
    "Variant Fulfillment Service": "manual",
    "Variant Price": 37.99,
    "Variant Compare At Price": 45.99,
    "Variant Requires Shipping": true,
    "Variant Taxable": true,
    "Variant Barcode": "",
    "Image Src":
      "https://cdn.shopify.com/s/files/1/0814/6190/3638/products/galaxy-earrings_925x_028d60fa-79a8-44f3-9dfc-a9a67b678aee.jpg?v=1692687720",
    "Image Position": 1,
    "Image Alt Text": "",
    "Gift Card": false,
    "SEO Title": "",
    "SEO Description": "",
    "Google Shopping / Google Product Category": "",
    "Google Shopping / Gender": "",
    "Google Shopping / Age Group": "",
    "Google Shopping / MPN": "",
    "Google Shopping / Condition": "",
    "Google Shopping / Custom Product": "",
    "Google Shopping / Custom Label 0": "",
    "Google Shopping / Custom Label 1": "",
    "Google Shopping / Custom Label 2": "",
    "Google Shopping / Custom Label 3": "",
    "Google Shopping / Custom Label 4": "",
    "Variant Image": "",
    "Variant Weight Unit": "kg",
    "Variant Tax Code": "",
    "Cost per item": "",
    "Included / India": true,
    "Included / International": true,
    "Price / International": "",
    "Compare At Price / International": "",
    Status: "active",
  },
  {
    Handle: "gemstone",
    Title: "Gemstone Necklace",
    "Body (HTML)":
      "<p>Gemstone pendant, housed in sterling silver, with sterling silver chain.</p>\n<ul>\n<li>Sterling silver chain, 14 inches</li>\n<li>Turquoise or Quartz</li>\n<li>Boho Chic</li>\n<li>Made in USA</li>\n</ul>",
    Vendor: "Sterling Ltd",
    "Product Category": "",
    Type: "Necklace",
    Tags: "Blue, Gem, Purple, Silver, Turquoise",
    Published: true,
    "Option1 Name": "Colour",
    "Option1 Value": "Blue",
    "Option2 Name": "",
    "Option2 Value": "",
    "Option3 Name": "",
    "Option3 Value": "",
    "Variant SKU": "",
    "Variant Grams": 0,
    "Variant Inventory Tracker": "",
    "Variant Inventory Qty": 1,
    "Variant Inventory Policy": "deny",
    "Variant Fulfillment Service": "manual",
    "Variant Price": 1254,
    "Variant Compare At Price": 29.99,
    "Variant Requires Shipping": true,
    "Variant Taxable": true,
    "Variant Barcode": "",
    "Image Src":
      "https://cdn.shopify.com/s/files/1/0814/6190/3638/products/blue-gemstone-pendant_925x_a71f1c39-8642-49b6-8761-79d7c241a515.jpg?v=1692687724",
    "Image Position": 1,
    "Image Alt Text": "",
    "Gift Card": false,
    "SEO Title": "",
    "SEO Description": "",
    "Google Shopping / Google Product Category": "",
    "Google Shopping / Gender": "",
    "Google Shopping / Age Group": "",
    "Google Shopping / MPN": "",
    "Google Shopping / Condition": "",
    "Google Shopping / Custom Product": "",
    "Google Shopping / Custom Label 0": "",
    "Google Shopping / Custom Label 1": "",
    "Google Shopping / Custom Label 2": "",
    "Google Shopping / Custom Label 3": "",
    "Google Shopping / Custom Label 4": "",
    "Variant Image":
      "https://cdn.shopify.com/s/files/1/0814/6190/3638/products/blue-gemstone-pendant_925x_a71f1c39-8642-49b6-8761-79d7c241a515.jpg?v=1692687724",
    "Variant Weight Unit": "kg",
    "Variant Tax Code": "",
    "Cost per item": "",
    "Included / India": true,
    "Included / International": true,
    "Price / International": "",
    "Compare At Price / International": "",
    Status: "active",
  },
  {
    Handle: "gemstone",
    Title: "",
    "Body (HTML)": "",
    Vendor: "",
    "Product Category": "",
    Type: "",
    Tags: "",
    Published: "",
    "Option1 Name": "",
    "Option1 Value": "Purple",
    "Option2 Name": "",
    "Option2 Value": "",
    "Option3 Name": "",
    "Option3 Value": "",
    "Variant SKU": "",
    "Variant Grams": 0,
    "Variant Inventory Tracker": "",
    "Variant Inventory Qty": 0,
    "Variant Inventory Policy": "deny",
    "Variant Fulfillment Service": "manual",
    "Variant Price": 27.99,
    "Variant Compare At Price": 29.99,
    "Variant Requires Shipping": true,
    "Variant Taxable": true,
    "Variant Barcode": "",
    "Image Src":
      "https://cdn.shopify.com/s/files/1/0814/6190/3638/products/gemstone-necklace_925x_f51c78b6-a991-43e0-bd20-fdab518360c7.jpg?v=1692687724",
    "Image Position": 2,
    "Image Alt Text": "",
    "Gift Card": "",
    "SEO Title": "",
    "SEO Description": "",
    "Google Shopping / Google Product Category": "",
    "Google Shopping / Gender": "",
    "Google Shopping / Age Group": "",
    "Google Shopping / MPN": "",
    "Google Shopping / Condition": "",
    "Google Shopping / Custom Product": "",
    "Google Shopping / Custom Label 0": "",
    "Google Shopping / Custom Label 1": "",
    "Google Shopping / Custom Label 2": "",
    "Google Shopping / Custom Label 3": "",
    "Google Shopping / Custom Label 4": "",
    "Variant Image":
      "https://cdn.shopify.com/s/files/1/0814/6190/3638/products/purple-gemstone-necklace_925x_9e6a637b-2ded-40e5-a795-b6f9086d89b4.jpg?v=1692687724",
    "Variant Weight Unit": "kg",
    "Variant Tax Code": "",
    "Cost per item": "",
    "Included / India": "",
    "Included / International": "",
    "Price / International": "",
    "Compare At Price / International": "",
    Status: "",
  },
  {
    Handle: "gemstone",
    Title: "",
    "Body (HTML)": "",
    Vendor: "",
    "Product Category": "",
    Type: "",
    Tags: "",
    Published: "",
    "Option1 Name": "",
    "Option1 Value": "",
    "Option2 Name": "",
    "Option2 Value": "",
    "Option3 Name": "",
    "Option3 Value": "",
    "Variant SKU": "",
    "Variant Grams": "",
    "Variant Inventory Tracker": "",
    "Variant Inventory Qty": "",
    "Variant Inventory Policy": "",
    "Variant Fulfillment Service": "",
    "Variant Price": "",
    "Variant Compare At Price": "",
    "Variant Requires Shipping": "",
    "Variant Taxable": "",
    "Variant Barcode": "",
    "Image Src":
      "https://cdn.shopify.com/s/files/1/0814/6190/3638/products/womens-necklace_925x_61e1a050-aa8e-48ca-b7f5-c018afa3fa5e.jpg?v=1692687724",
    "Image Position": 3,
    "Image Alt Text": "",
    "Gift Card": "",
    "SEO Title": "",
    "SEO Description": "",
    "Google Shopping / Google Product Category": "",
    "Google Shopping / Gender": "",
    "Google Shopping / Age Group": "",
    "Google Shopping / MPN": "",
    "Google Shopping / Condition": "",
    "Google Shopping / Custom Product": "",
    "Google Shopping / Custom Label 0": "",
    "Google Shopping / Custom Label 1": "",
    "Google Shopping / Custom Label 2": "",
    "Google Shopping / Custom Label 3": "",
    "Google Shopping / Custom Label 4": "",
    "Variant Image": "",
    "Variant Weight Unit": "",
    "Variant Tax Code": "",
    "Cost per item": "",
    "Included / India": "",
    "Included / International": "",
    "Price / International": "",
    "Compare At Price / International": "",
    Status: "",
  },
  {
    Handle: "gemstone",
    Title: "",
    "Body (HTML)": "",
    Vendor: "",
    "Product Category": "",
    Type: "",
    Tags: "",
    Published: "",
    "Option1 Name": "",
    "Option1 Value": "",
    "Option2 Name": "",
    "Option2 Value": "",
    "Option3 Name": "",
    "Option3 Value": "",
    "Variant SKU": "",
    "Variant Grams": "",
    "Variant Inventory Tracker": "",
    "Variant Inventory Qty": "",
    "Variant Inventory Policy": "",
    "Variant Fulfillment Service": "",
    "Variant Price": "",
    "Variant Compare At Price": "",
    "Variant Requires Shipping": "",
    "Variant Taxable": "",
    "Variant Barcode": "",
    "Image Src":
      "https://cdn.shopify.com/s/files/1/0814/6190/3638/products/purple-gemstone-necklace_925x_9e6a637b-2ded-40e5-a795-b6f9086d89b4.jpg?v=1692687724",
    "Image Position": 4,
    "Image Alt Text": "",
    "Gift Card": "",
    "SEO Title": "",
    "SEO Description": "",
    "Google Shopping / Google Product Category": "",
    "Google Shopping / Gender": "",
    "Google Shopping / Age Group": "",
    "Google Shopping / MPN": "",
    "Google Shopping / Condition": "",
    "Google Shopping / Custom Product": "",
    "Google Shopping / Custom Label 0": "",
    "Google Shopping / Custom Label 1": "",
    "Google Shopping / Custom Label 2": "",
    "Google Shopping / Custom Label 3": "",
    "Google Shopping / Custom Label 4": "",
    "Variant Image": "",
    "Variant Weight Unit": "",
    "Variant Tax Code": "",
    "Cost per item": "",
    "Included / India": "",
    "Included / International": "",
    "Price / International": "",
    "Compare At Price / International": "",
    Status: "",
  },
  {
    Handle: "gold-bird-necklace",
    Title: "Gold Bird Necklace",
    "Body (HTML)":
      "<p>14k Gold delicate necklace, with bird between two chains.</p>",
    Vendor: "Company 123",
    "Product Category": "",
    Type: "Necklace",
    Tags: "Bird, Gold",
    Published: true,
    "Option1 Name": "Title",
    "Option1 Value": "Default Title",
    "Option2 Name": "",
    "Option2 Value": "",
    "Option3 Name": "",
    "Option3 Value": "",
    "Variant SKU": "",
    "Variant Grams": 0,
    "Variant Inventory Tracker": "",
    "Variant Inventory Qty": 1,
    "Variant Inventory Policy": "deny",
    "Variant Fulfillment Service": "manual",
    "Variant Price": 79.99,
    "Variant Compare At Price": "",
    "Variant Requires Shipping": true,
    "Variant Taxable": true,
    "Variant Barcode": "",
    "Image Src":
      "https://cdn.shopify.com/s/files/1/0814/6190/3638/products/gold-bird-necklace_925x_ba89c783-5b72-4d80-a0c2-0f5c0151b2a2.jpg?v=1692687726",
    "Image Position": 1,
    "Image Alt Text": "",
    "Gift Card": false,
    "SEO Title": "",
    "SEO Description": "",
    "Google Shopping / Google Product Category": "",
    "Google Shopping / Gender": "",
    "Google Shopping / Age Group": "",
    "Google Shopping / MPN": "",
    "Google Shopping / Condition": "",
    "Google Shopping / Custom Product": "",
    "Google Shopping / Custom Label 0": "",
    "Google Shopping / Custom Label 1": "",
    "Google Shopping / Custom Label 2": "",
    "Google Shopping / Custom Label 3": "",
    "Google Shopping / Custom Label 4": "",
    "Variant Image": "",
    "Variant Weight Unit": "kg",
    "Variant Tax Code": "",
    "Cost per item": "",
    "Included / India": true,
    "Included / International": true,
    "Price / International": "",
    "Compare At Price / International": "",
    Status: "active",
  },
  {
    Handle: "guardian-angel-earrings",
    Title: "Guardian Angel Earrings",
    "Body (HTML)":
      "<p>Sterling silver guardian angel earrings with diamond gemstones.</p>",
    Vendor: "Sterling Ltd",
    "Product Category": "",
    Type: "Earrings",
    Tags: "Angel, Silver",
    Published: true,
    "Option1 Name": "Title",
    "Option1 Value": "Default Title",
    "Option2 Name": "",
    "Option2 Value": "",
    "Option3 Name": "",
    "Option3 Value": "",
    "Variant SKU": "",
    "Variant Grams": 0,
    "Variant Inventory Tracker": "",
    "Variant Inventory Qty": 1,
    "Variant Inventory Policy": "deny",
    "Variant Fulfillment Service": "manual",
    "Variant Price": 19.99,
    "Variant Compare At Price": "",
    "Variant Requires Shipping": true,
    "Variant Taxable": true,
    "Variant Barcode": "",
    "Image Src":
      "https://cdn.shopify.com/s/files/1/0814/6190/3638/products/guardian-angel-earrings_925x_4461e64f-3f68-4fff-980f-708d285a8c67.jpg?v=1692687730",
    "Image Position": 1,
    "Image Alt Text": "",
    "Gift Card": false,
    "SEO Title": "",
    "SEO Description": "",
    "Google Shopping / Google Product Category": "",
    "Google Shopping / Gender": "",
    "Google Shopping / Age Group": "",
    "Google Shopping / MPN": "",
    "Google Shopping / Condition": "",
    "Google Shopping / Custom Product": "",
    "Google Shopping / Custom Label 0": "",
    "Google Shopping / Custom Label 1": "",
    "Google Shopping / Custom Label 2": "",
    "Google Shopping / Custom Label 3": "",
    "Google Shopping / Custom Label 4": "",
    "Variant Image": "",
    "Variant Weight Unit": "kg",
    "Variant Tax Code": "",
    "Cost per item": "",
    "Included / India": true,
    "Included / International": true,
    "Price / International": "",
    "Compare At Price / International": "",
    Status: "active",
  },
  {
    Handle: "guardian-angel-earrings",
    Title: "",
    "Body (HTML)": "",
    Vendor: "",
    "Product Category": "",
    Type: "",
    Tags: "",
    Published: "",
    "Option1 Name": "",
    "Option1 Value": "",
    "Option2 Name": "",
    "Option2 Value": "",
    "Option3 Name": "",
    "Option3 Value": "",
    "Variant SKU": "",
    "Variant Grams": "",
    "Variant Inventory Tracker": "",
    "Variant Inventory Qty": "",
    "Variant Inventory Policy": "",
    "Variant Fulfillment Service": "",
    "Variant Price": "",
    "Variant Compare At Price": "",
    "Variant Requires Shipping": "",
    "Variant Taxable": "",
    "Variant Barcode": "",
    "Image Src":
      "https://cdn.shopify.com/s/files/1/0814/6190/3638/products/guardian-angel-earring-closeup_925x_ec1ce33d-7377-4166-a4a2-930cfc5080f5.jpg?v=1692687730",
    "Image Position": 2,
    "Image Alt Text": "",
    "Gift Card": "",
    "SEO Title": "",
    "SEO Description": "",
    "Google Shopping / Google Product Category": "",
    "Google Shopping / Gender": "",
    "Google Shopping / Age Group": "",
    "Google Shopping / MPN": "",
    "Google Shopping / Condition": "",
    "Google Shopping / Custom Product": "",
    "Google Shopping / Custom Label 0": "",
    "Google Shopping / Custom Label 1": "",
    "Google Shopping / Custom Label 2": "",
    "Google Shopping / Custom Label 3": "",
    "Google Shopping / Custom Label 4": "",
    "Variant Image": "",
    "Variant Weight Unit": "",
    "Variant Tax Code": "",
    "Cost per item": "",
    "Included / India": "",
    "Included / International": "",
    "Price / International": "",
    "Compare At Price / International": "",
    Status: "",
  },
  {
    Handle: "leather-anchor",
    Title: "Anchor Bracelet Mens",
    "Body (HTML)":
      "<p>Black leather bracelet with gold or silver anchor for men.</p>",
    Vendor: "Company 123",
    "Product Category": "",
    Type: "Bracelet",
    Tags: "Anchor, Gold, Leather, Silver",
    Published: false,
    "Option1 Name": "Color",
    "Option1 Value": "Gold",
    "Option2 Name": "",
    "Option2 Value": "",
    "Option3 Name": "",
    "Option3 Value": "",
    "Variant SKU": "",
    "Variant Grams": 0,
    "Variant Inventory Tracker": "",
    "Variant Inventory Qty": 1,
    "Variant Inventory Policy": "deny",
    "Variant Fulfillment Service": "manual",
    "Variant Price": 69.99,
    "Variant Compare At Price": 85,
    "Variant Requires Shipping": true,
    "Variant Taxable": true,
    "Variant Barcode": "",
    "Image Src":
      "https://cdn.shopify.com/s/files/1/0814/6190/3638/products/anchor-bracelet-mens_925x_d4f35098-ea53-46cc-8a66-7c2e6084ca89.jpg?v=1692687700",
    "Image Position": 1,
    "Image Alt Text": "",
    "Gift Card": false,
    "SEO Title": "",
    "SEO Description": "",
    "Google Shopping / Google Product Category": "",
    "Google Shopping / Gender": "",
    "Google Shopping / Age Group": "",
    "Google Shopping / MPN": "",
    "Google Shopping / Condition": "",
    "Google Shopping / Custom Product": "",
    "Google Shopping / Custom Label 0": "",
    "Google Shopping / Custom Label 1": "",
    "Google Shopping / Custom Label 2": "",
    "Google Shopping / Custom Label 3": "",
    "Google Shopping / Custom Label 4": "",
    "Variant Image":
      "https://cdn.shopify.com/s/files/1/0814/6190/3638/products/anchor-bracelet-mens_925x_d4f35098-ea53-46cc-8a66-7c2e6084ca89.jpg?v=1692687700",
    "Variant Weight Unit": "kg",
    "Variant Tax Code": "",
    "Cost per item": "",
    "Included / India": true,
    "Included / International": true,
    "Price / International": "",
    "Compare At Price / International": "",
    Status: "archived",
  },
  {
    Handle: "leather-anchor",
    Title: "",
    "Body (HTML)": "",
    Vendor: "",
    "Product Category": "",
    Type: "",
    Tags: "",
    Published: "",
    "Option1 Name": "",
    "Option1 Value": "Silver",
    "Option2 Name": "",
    "Option2 Value": "",
    "Option3 Name": "",
    "Option3 Value": "",
    "Variant SKU": "",
    "Variant Grams": 0,
    "Variant Inventory Tracker": "",
    "Variant Inventory Qty": 0,
    "Variant Inventory Policy": "deny",
    "Variant Fulfillment Service": "manual",
    "Variant Price": 55,
    "Variant Compare At Price": 85,
    "Variant Requires Shipping": true,
    "Variant Taxable": true,
    "Variant Barcode": "",
    "Image Src":
      "https://cdn.shopify.com/s/files/1/0814/6190/3638/products/anchor-bracelet-for-men_925x_5d15b7c3-2639-45e0-b382-0990505e8b4b.jpg?v=1692687700",
    "Image Position": 2,
    "Image Alt Text": "",
    "Gift Card": "",
    "SEO Title": "",
    "SEO Description": "",
    "Google Shopping / Google Product Category": "",
    "Google Shopping / Gender": "",
    "Google Shopping / Age Group": "",
    "Google Shopping / MPN": "",
    "Google Shopping / Condition": "",
    "Google Shopping / Custom Product": "",
    "Google Shopping / Custom Label 0": "",
    "Google Shopping / Custom Label 1": "",
    "Google Shopping / Custom Label 2": "",
    "Google Shopping / Custom Label 3": "",
    "Google Shopping / Custom Label 4": "",
    "Variant Image":
      "https://cdn.shopify.com/s/files/1/0814/6190/3638/products/anchor-bracelet-for-men_925x_5d15b7c3-2639-45e0-b382-0990505e8b4b.jpg?v=1692687700",
    "Variant Weight Unit": "kg",
    "Variant Tax Code": "",
    "Cost per item": "",
    "Included / India": "",
    "Included / International": "",
    "Price / International": "",
    "Compare At Price / International": "",
    Status: "",
  },
  {
    Handle: "leather-anchor",
    Title: "",
    "Body (HTML)": "",
    Vendor: "",
    "Product Category": "",
    Type: "",
    Tags: "",
    Published: "",
    "Option1 Name": "",
    "Option1 Value": "",
    "Option2 Name": "",
    "Option2 Value": "",
    "Option3 Name": "",
    "Option3 Value": "",
    "Variant SKU": "",
    "Variant Grams": "",
    "Variant Inventory Tracker": "",
    "Variant Inventory Qty": "",
    "Variant Inventory Policy": "",
    "Variant Fulfillment Service": "",
    "Variant Price": "",
    "Variant Compare At Price": "",
    "Variant Requires Shipping": "",
    "Variant Taxable": "",
    "Variant Barcode": "",
    "Image Src":
      "https://cdn.shopify.com/s/files/1/0814/6190/3638/products/leather-anchor-bracelet-for-men_925x_258aa0a0-5f2f-4c44-8f17-fb7a573d412a.jpg?v=1692687700",
    "Image Position": 3,
    "Image Alt Text": "",
    "Gift Card": "",
    "SEO Title": "",
    "SEO Description": "",
    "Google Shopping / Google Product Category": "",
    "Google Shopping / Gender": "",
    "Google Shopping / Age Group": "",
    "Google Shopping / MPN": "",
    "Google Shopping / Condition": "",
    "Google Shopping / Custom Product": "",
    "Google Shopping / Custom Label 0": "",
    "Google Shopping / Custom Label 1": "",
    "Google Shopping / Custom Label 2": "",
    "Google Shopping / Custom Label 3": "",
    "Google Shopping / Custom Label 4": "",
    "Variant Image": "",
    "Variant Weight Unit": "",
    "Variant Tax Code": "",
    "Cost per item": "",
    "Included / India": "",
    "Included / International": "",
    "Price / International": "",
    "Compare At Price / International": "",
    Status: "",
  },
  {
    Handle: "looped-earrings",
    Title: "Gold Elephant Earrings",
    "Body (HTML)":
      "<p>Small 14k gold elephant earrings, with opal ear detail.</p>",
    Vendor: "Company 123",
    "Product Category": "",
    Type: "Earrings",
    Tags: "Gold, Silver",
    Published: true,
    "Option1 Name": "Title",
    "Option1 Value": "Default Title",
    "Option2 Name": "",
    "Option2 Value": "",
    "Option3 Name": "",
    "Option3 Value": "",
    "Variant SKU": "",
    "Variant Grams": 0,
    "Variant Inventory Tracker": "",
    "Variant Inventory Qty": 1,
    "Variant Inventory Policy": "deny",
    "Variant Fulfillment Service": "manual",
    "Variant Price": 54.99,
    "Variant Compare At Price": "",
    "Variant Requires Shipping": true,
    "Variant Taxable": true,
    "Variant Barcode": "",
    "Image Src":
      "https://cdn.shopify.com/s/files/1/0814/6190/3638/products/elephant-earrings_925x_c4eaf75b-a2a3-4a23-9c42-f30885ecbc71.jpg?v=1692687727",
    "Image Position": 1,
    "Image Alt Text": "",
    "Gift Card": false,
    "SEO Title": "",
    "SEO Description": "",
    "Google Shopping / Google Product Category": "",
    "Google Shopping / Gender": "",
    "Google Shopping / Age Group": "",
    "Google Shopping / MPN": "",
    "Google Shopping / Condition": "",
    "Google Shopping / Custom Product": "",
    "Google Shopping / Custom Label 0": "",
    "Google Shopping / Custom Label 1": "",
    "Google Shopping / Custom Label 2": "",
    "Google Shopping / Custom Label 3": "",
    "Google Shopping / Custom Label 4": "",
    "Variant Image": "",
    "Variant Weight Unit": "kg",
    "Variant Tax Code": "",
    "Cost per item": "",
    "Included / India": true,
    "Included / International": true,
    "Price / International": "",
    "Compare At Price / International": "",
    Status: "active",
  },
  {
    Handle: "moon-charm-bracelet",
    Title: "Moon Charm Bracelet",
    "Body (HTML)": "<p>Moon 14k gold chain friendship bracelet.</p>",
    Vendor: "Company 123",
    "Product Category": "",
    Type: "Bracelet",
    Tags: "Gold, Moon",
    Published: true,
    "Option1 Name": "Title",
    "Option1 Value": "Default Title",
    "Option2 Name": "",
    "Option2 Value": "",
    "Option3 Name": "",
    "Option3 Value": "",
    "Variant SKU": "",
    "Variant Grams": 0,
    "Variant Inventory Tracker": "",
    "Variant Inventory Qty": 1,
    "Variant Inventory Policy": "deny",
    "Variant Fulfillment Service": "manual",
    "Variant Price": 47.99,
    "Variant Compare At Price": 49.99,
    "Variant Requires Shipping": true,
    "Variant Taxable": true,
    "Variant Barcode": "",
    "Image Src":
      "https://cdn.shopify.com/s/files/1/0814/6190/3638/products/womens-hand-moon-bracelet-_925x_c44820f7-9ed4-4587-a84e-470a9178c189.jpg?v=1692687734",
    "Image Position": 1,
    "Image Alt Text": "",
    "Gift Card": false,
    "SEO Title": "",
    "SEO Description": "",
    "Google Shopping / Google Product Category": "",
    "Google Shopping / Gender": "",
    "Google Shopping / Age Group": "",
    "Google Shopping / MPN": "",
    "Google Shopping / Condition": "",
    "Google Shopping / Custom Product": "",
    "Google Shopping / Custom Label 0": "",
    "Google Shopping / Custom Label 1": "",
    "Google Shopping / Custom Label 2": "",
    "Google Shopping / Custom Label 3": "",
    "Google Shopping / Custom Label 4": "",
    "Variant Image": "",
    "Variant Weight Unit": "kg",
    "Variant Tax Code": "",
    "Cost per item": "",
    "Included / India": true,
    "Included / International": true,
    "Price / International": "",
    "Compare At Price / International": "",
    Status: "active",
  },
  {
    Handle: "moon-charm-bracelet",
    Title: "",
    "Body (HTML)": "",
    Vendor: "",
    "Product Category": "",
    Type: "",
    Tags: "",
    Published: "",
    "Option1 Name": "",
    "Option1 Value": "",
    "Option2 Name": "",
    "Option2 Value": "",
    "Option3 Name": "",
    "Option3 Value": "",
    "Variant SKU": "",
    "Variant Grams": "",
    "Variant Inventory Tracker": "",
    "Variant Inventory Qty": "",
    "Variant Inventory Policy": "",
    "Variant Fulfillment Service": "",
    "Variant Price": "",
    "Variant Compare At Price": "",
    "Variant Requires Shipping": "",
    "Variant Taxable": "",
    "Variant Barcode": "",
    "Image Src":
      "https://cdn.shopify.com/s/files/1/0814/6190/3638/products/moon-friendship-bracelet_925x_d861b75d-5887-45a8-8afb-32f5eb89e5a2.jpg?v=1692687734",
    "Image Position": 2,
    "Image Alt Text": "",
    "Gift Card": "",
    "SEO Title": "",
    "SEO Description": "",
    "Google Shopping / Google Product Category": "",
    "Google Shopping / Gender": "",
    "Google Shopping / Age Group": "",
    "Google Shopping / MPN": "",
    "Google Shopping / Condition": "",
    "Google Shopping / Custom Product": "",
    "Google Shopping / Custom Label 0": "",
    "Google Shopping / Custom Label 1": "",
    "Google Shopping / Custom Label 2": "",
    "Google Shopping / Custom Label 3": "",
    "Google Shopping / Custom Label 4": "",
    "Variant Image": "",
    "Variant Weight Unit": "",
    "Variant Tax Code": "",
    "Cost per item": "",
    "Included / India": "",
    "Included / International": "",
    "Price / International": "",
    "Compare At Price / International": "",
    Status: "",
  },
  {
    Handle: "moon-charm-bracelet",
    Title: "",
    "Body (HTML)": "",
    Vendor: "",
    "Product Category": "",
    Type: "",
    Tags: "",
    Published: "",
    "Option1 Name": "",
    "Option1 Value": "",
    "Option2 Name": "",
    "Option2 Value": "",
    "Option3 Name": "",
    "Option3 Value": "",
    "Variant SKU": "",
    "Variant Grams": "",
    "Variant Inventory Tracker": "",
    "Variant Inventory Qty": "",
    "Variant Inventory Policy": "",
    "Variant Fulfillment Service": "",
    "Variant Price": "",
    "Variant Compare At Price": "",
    "Variant Requires Shipping": "",
    "Variant Taxable": "",
    "Variant Barcode": "",
    "Image Src":
      "https://cdn.shopify.com/s/files/1/0814/6190/3638/products/womens-hand-charm-bracelet_925x_9f82e037-2f07-4790-9a51-2fb0df3e33c1.jpg?v=1692687734",
    "Image Position": 3,
    "Image Alt Text": "",
    "Gift Card": "",
    "SEO Title": "",
    "SEO Description": "",
    "Google Shopping / Google Product Category": "",
    "Google Shopping / Gender": "",
    "Google Shopping / Age Group": "",
    "Google Shopping / MPN": "",
    "Google Shopping / Condition": "",
    "Google Shopping / Custom Product": "",
    "Google Shopping / Custom Label 0": "",
    "Google Shopping / Custom Label 1": "",
    "Google Shopping / Custom Label 2": "",
    "Google Shopping / Custom Label 3": "",
    "Google Shopping / Custom Label 4": "",
    "Variant Image": "",
    "Variant Weight Unit": "",
    "Variant Tax Code": "",
    "Cost per item": "",
    "Included / India": "",
    "Included / International": "",
    "Price / International": "",
    "Compare At Price / International": "",
    Status: "",
  },
  {
    Handle: "origami-crane-necklace",
    Title: "Origami Crane Necklace",
    "Body (HTML)": "<p>Sterling silver origami crane necklace.</p>",
    Vendor: "Sterling Ltd",
    "Product Category": "",
    Type: "Necklace",
    Tags: "Crane, Origami, Silver",
    Published: true,
    "Option1 Name": "Title",
    "Option1 Value": "Default Title",
    "Option2 Name": "",
    "Option2 Value": "",
    "Option3 Name": "",
    "Option3 Value": "",
    "Variant SKU": "",
    "Variant Grams": 0,
    "Variant Inventory Tracker": "",
    "Variant Inventory Qty": 1,
    "Variant Inventory Policy": "deny",
    "Variant Fulfillment Service": "manual",
    "Variant Price": 75.99,
    "Variant Compare At Price": "",
    "Variant Requires Shipping": true,
    "Variant Taxable": true,
    "Variant Barcode": "",
    "Image Src":
      "https://cdn.shopify.com/s/files/1/0814/6190/3638/products/origami-crane-necklace-gold_925x_3f56cab7-ee8e-49fe-815b-41d797eaff16.jpg?v=1692687738",
    "Image Position": 1,
    "Image Alt Text": "",
    "Gift Card": false,
    "SEO Title": "",
    "SEO Description": "",
    "Google Shopping / Google Product Category": "",
    "Google Shopping / Gender": "",
    "Google Shopping / Age Group": "",
    "Google Shopping / MPN": "",
    "Google Shopping / Condition": "",
    "Google Shopping / Custom Product": "",
    "Google Shopping / Custom Label 0": "",
    "Google Shopping / Custom Label 1": "",
    "Google Shopping / Custom Label 2": "",
    "Google Shopping / Custom Label 3": "",
    "Google Shopping / Custom Label 4": "",
    "Variant Image": "",
    "Variant Weight Unit": "kg",
    "Variant Tax Code": "",
    "Cost per item": "",
    "Included / India": true,
    "Included / International": true,
    "Price / International": "",
    "Compare At Price / International": "",
    Status: "active",
  },
  {
    Handle: "origami-crane-necklace",
    Title: "",
    "Body (HTML)": "",
    Vendor: "",
    "Product Category": "",
    Type: "",
    Tags: "",
    Published: "",
    "Option1 Name": "",
    "Option1 Value": "",
    "Option2 Name": "",
    "Option2 Value": "",
    "Option3 Name": "",
    "Option3 Value": "",
    "Variant SKU": "",
    "Variant Grams": "",
    "Variant Inventory Tracker": "",
    "Variant Inventory Qty": "",
    "Variant Inventory Policy": "",
    "Variant Fulfillment Service": "",
    "Variant Price": "",
    "Variant Compare At Price": "",
    "Variant Requires Shipping": "",
    "Variant Taxable": "",
    "Variant Barcode": "",
    "Image Src":
      "https://cdn.shopify.com/s/files/1/0814/6190/3638/products/silver-origami-necklace_925x_a4d69aef-5673-4f80-8f01-335943437e79.jpg?v=1692687738",
    "Image Position": 2,
    "Image Alt Text": "",
    "Gift Card": "",
    "SEO Title": "",
    "SEO Description": "",
    "Google Shopping / Google Product Category": "",
    "Google Shopping / Gender": "",
    "Google Shopping / Age Group": "",
    "Google Shopping / MPN": "",
    "Google Shopping / Condition": "",
    "Google Shopping / Custom Product": "",
    "Google Shopping / Custom Label 0": "",
    "Google Shopping / Custom Label 1": "",
    "Google Shopping / Custom Label 2": "",
    "Google Shopping / Custom Label 3": "",
    "Google Shopping / Custom Label 4": "",
    "Variant Image": "",
    "Variant Weight Unit": "",
    "Variant Tax Code": "",
    "Cost per item": "",
    "Included / India": "",
    "Included / International": "",
    "Price / International": "",
    "Compare At Price / International": "",
    Status: "",
  },
  {
    Handle: "origami-crane-necklace",
    Title: "",
    "Body (HTML)": "",
    Vendor: "",
    "Product Category": "",
    Type: "",
    Tags: "",
    Published: "",
    "Option1 Name": "",
    "Option1 Value": "",
    "Option2 Name": "",
    "Option2 Value": "",
    "Option3 Name": "",
    "Option3 Value": "",
    "Variant SKU": "",
    "Variant Grams": "",
    "Variant Inventory Tracker": "",
    "Variant Inventory Qty": "",
    "Variant Inventory Policy": "",
    "Variant Fulfillment Service": "",
    "Variant Price": "",
    "Variant Compare At Price": "",
    "Variant Requires Shipping": "",
    "Variant Taxable": "",
    "Variant Barcode": "",
    "Image Src":
      "https://cdn.shopify.com/s/files/1/0814/6190/3638/products/origami-crane-necklace_925x_f8cbc27f-ec0a-4774-ba57-107876256253.jpg?v=1692687738",
    "Image Position": 3,
    "Image Alt Text": "",
    "Gift Card": "",
    "SEO Title": "",
    "SEO Description": "",
    "Google Shopping / Google Product Category": "",
    "Google Shopping / Gender": "",
    "Google Shopping / Age Group": "",
    "Google Shopping / MPN": "",
    "Google Shopping / Condition": "",
    "Google Shopping / Custom Product": "",
    "Google Shopping / Custom Label 0": "",
    "Google Shopping / Custom Label 1": "",
    "Google Shopping / Custom Label 2": "",
    "Google Shopping / Custom Label 3": "",
    "Google Shopping / Custom Label 4": "",
    "Variant Image": "",
    "Variant Weight Unit": "",
    "Variant Tax Code": "",
    "Cost per item": "",
    "Included / India": "",
    "Included / International": "",
    "Price / International": "",
    "Compare At Price / International": "",
    Status: "",
  },
  {
    Handle: "origami-crane-necklace",
    Title: "",
    "Body (HTML)": "",
    Vendor: "",
    "Product Category": "",
    Type: "",
    Tags: "",
    Published: "",
    "Option1 Name": "",
    "Option1 Value": "",
    "Option2 Name": "",
    "Option2 Value": "",
    "Option3 Name": "",
    "Option3 Value": "",
    "Variant SKU": "",
    "Variant Grams": "",
    "Variant Inventory Tracker": "",
    "Variant Inventory Qty": "",
    "Variant Inventory Policy": "",
    "Variant Fulfillment Service": "",
    "Variant Price": "",
    "Variant Compare At Price": "",
    "Variant Requires Shipping": "",
    "Variant Taxable": "",
    "Variant Barcode": "",
    "Image Src":
      "https://cdn.shopify.com/s/files/1/0814/6190/3638/products/womens-green-turtleneck_925x_c8007342-4333-4451-b843-535eb912df0b.jpg?v=1692687738",
    "Image Position": 4,
    "Image Alt Text": "",
    "Gift Card": "",
    "SEO Title": "",
    "SEO Description": "",
    "Google Shopping / Google Product Category": "",
    "Google Shopping / Gender": "",
    "Google Shopping / Age Group": "",
    "Google Shopping / MPN": "",
    "Google Shopping / Condition": "",
    "Google Shopping / Custom Product": "",
    "Google Shopping / Custom Label 0": "",
    "Google Shopping / Custom Label 1": "",
    "Google Shopping / Custom Label 2": "",
    "Google Shopping / Custom Label 3": "",
    "Google Shopping / Custom Label 4": "",
    "Variant Image": "",
    "Variant Weight Unit": "",
    "Variant Tax Code": "",
    "Cost per item": "",
    "Included / India": "",
    "Included / International": "",
    "Price / International": "",
    "Compare At Price / International": "",
    Status: "",
  },
  {
    Handle: "pretty-gold-necklace",
    Title: "Pretty Gold Necklace",
    "Body (HTML)":
      "<p>14k gold and turquoise necklace. Stunning beaded turquoise on gold and pendant filled double chain design.</p>",
    Vendor: "Company 123",
    "Product Category": "",
    Type: "Necklace",
    Tags: "Gold, Turquoise",
    Published: true,
    "Option1 Name": "Title",
    "Option1 Value": "Default Title",
    "Option2 Name": "",
    "Option2 Value": "",
    "Option3 Name": "",
    "Option3 Value": "",
    "Variant SKU": "",
    "Variant Grams": 0,
    "Variant Inventory Tracker": "",
    "Variant Inventory Qty": 1,
    "Variant Inventory Policy": "deny",
    "Variant Fulfillment Service": "manual",
    "Variant Price": 44.95,
    "Variant Compare At Price": 63.99,
    "Variant Requires Shipping": true,
    "Variant Taxable": true,
    "Variant Barcode": "",
    "Image Src":
      "https://cdn.shopify.com/s/files/1/0814/6190/3638/products/pretty-gold-necklace_925x_6c993e64-e2e9-44a6-b178-771d8014c577.jpg?v=1692687742",
    "Image Position": 1,
    "Image Alt Text": "",
    "Gift Card": false,
    "SEO Title": "",
    "SEO Description": "",
    "Google Shopping / Google Product Category": "",
    "Google Shopping / Gender": "",
    "Google Shopping / Age Group": "",
    "Google Shopping / MPN": "",
    "Google Shopping / Condition": "",
    "Google Shopping / Custom Product": "",
    "Google Shopping / Custom Label 0": "",
    "Google Shopping / Custom Label 1": "",
    "Google Shopping / Custom Label 2": "",
    "Google Shopping / Custom Label 3": "",
    "Google Shopping / Custom Label 4": "",
    "Variant Image": "",
    "Variant Weight Unit": "kg",
    "Variant Tax Code": "",
    "Cost per item": "",
    "Included / India": true,
    "Included / International": true,
    "Price / International": "",
    "Compare At Price / International": "",
    Status: "active",
  },
  {
    Handle: "pretty-gold-necklace",
    Title: "",
    "Body (HTML)": "",
    Vendor: "",
    "Product Category": "",
    Type: "",
    Tags: "",
    Published: "",
    "Option1 Name": "",
    "Option1 Value": "",
    "Option2 Name": "",
    "Option2 Value": "",
    "Option3 Name": "",
    "Option3 Value": "",
    "Variant SKU": "",
    "Variant Grams": "",
    "Variant Inventory Tracker": "",
    "Variant Inventory Qty": "",
    "Variant Inventory Policy": "",
    "Variant Fulfillment Service": "",
    "Variant Price": "",
    "Variant Compare At Price": "",
    "Variant Requires Shipping": "",
    "Variant Taxable": "",
    "Variant Barcode": "",
    "Image Src":
      "https://cdn.shopify.com/s/files/1/0814/6190/3638/products/necklace-earrings-set_925x_b459011c-a3c4-4730-b8e0-f94c7a61fae0.jpg?v=1692687742",
    "Image Position": 2,
    "Image Alt Text": "",
    "Gift Card": "",
    "SEO Title": "",
    "SEO Description": "",
    "Google Shopping / Google Product Category": "",
    "Google Shopping / Gender": "",
    "Google Shopping / Age Group": "",
    "Google Shopping / MPN": "",
    "Google Shopping / Condition": "",
    "Google Shopping / Custom Product": "",
    "Google Shopping / Custom Label 0": "",
    "Google Shopping / Custom Label 1": "",
    "Google Shopping / Custom Label 2": "",
    "Google Shopping / Custom Label 3": "",
    "Google Shopping / Custom Label 4": "",
    "Variant Image": "",
    "Variant Weight Unit": "",
    "Variant Tax Code": "",
    "Cost per item": "",
    "Included / India": "",
    "Included / International": "",
    "Price / International": "",
    "Compare At Price / International": "",
    Status: "",
  },
  {
    Handle: "pretty-gold-necklace",
    Title: "",
    "Body (HTML)": "",
    Vendor: "",
    "Product Category": "",
    Type: "",
    Tags: "",
    Published: "",
    "Option1 Name": "",
    "Option1 Value": "",
    "Option2 Name": "",
    "Option2 Value": "",
    "Option3 Name": "",
    "Option3 Value": "",
    "Variant SKU": "",
    "Variant Grams": "",
    "Variant Inventory Tracker": "",
    "Variant Inventory Qty": "",
    "Variant Inventory Policy": "",
    "Variant Fulfillment Service": "",
    "Variant Price": "",
    "Variant Compare At Price": "",
    "Variant Requires Shipping": "",
    "Variant Taxable": "",
    "Variant Barcode": "",
    "Image Src":
      "https://cdn.shopify.com/s/files/1/0814/6190/3638/products/inspired-woman_925x_119efcae-f452-4264-a02a-827959637727.jpg?v=1692687742",
    "Image Position": 3,
    "Image Alt Text": "",
    "Gift Card": "",
    "SEO Title": "",
    "SEO Description": "",
    "Google Shopping / Google Product Category": "",
    "Google Shopping / Gender": "",
    "Google Shopping / Age Group": "",
    "Google Shopping / MPN": "",
    "Google Shopping / Condition": "",
    "Google Shopping / Custom Product": "",
    "Google Shopping / Custom Label 0": "",
    "Google Shopping / Custom Label 1": "",
    "Google Shopping / Custom Label 2": "",
    "Google Shopping / Custom Label 3": "",
    "Google Shopping / Custom Label 4": "",
    "Variant Image": "",
    "Variant Weight Unit": "",
    "Variant Tax Code": "",
    "Cost per item": "",
    "Included / India": "",
    "Included / International": "",
    "Price / International": "",
    "Compare At Price / International": "",
    Status: "",
  },
  {
    Handle: "silver-threader-necklace",
    Title: "Silver Threader Necklace",
    "Body (HTML)":
      "<p>Sterling silver chain thread through circle necklace.</p>",
    Vendor: "Sterling Ltd",
    "Product Category": "",
    Type: "Necklace",
    Tags: "Silver",
    Published: true,
    "Option1 Name": "Title",
    "Option1 Value": "Default Title",
    "Option2 Name": "",
    "Option2 Value": "",
    "Option3 Name": "",
    "Option3 Value": "",
    "Variant SKU": "",
    "Variant Grams": 0,
    "Variant Inventory Tracker": "",
    "Variant Inventory Qty": 1,
    "Variant Inventory Policy": "deny",
    "Variant Fulfillment Service": "manual",
    "Variant Price": 14.99,
    "Variant Compare At Price": 19.99,
    "Variant Requires Shipping": true,
    "Variant Taxable": true,
    "Variant Barcode": "",
    "Image Src":
      "https://cdn.shopify.com/s/files/1/0814/6190/3638/products/silver-threader-necklace_925x_fcdc1bcd-fbb6-4011-a5ba-fffda0913ca0.jpg?v=1692687744",
    "Image Position": 1,
    "Image Alt Text": "",
    "Gift Card": false,
    "SEO Title": "",
    "SEO Description": "",
    "Google Shopping / Google Product Category": "",
    "Google Shopping / Gender": "",
    "Google Shopping / Age Group": "",
    "Google Shopping / MPN": "",
    "Google Shopping / Condition": "",
    "Google Shopping / Custom Product": "",
    "Google Shopping / Custom Label 0": "",
    "Google Shopping / Custom Label 1": "",
    "Google Shopping / Custom Label 2": "",
    "Google Shopping / Custom Label 3": "",
    "Google Shopping / Custom Label 4": "",
    "Variant Image": "",
    "Variant Weight Unit": "kg",
    "Variant Tax Code": "",
    "Cost per item": "",
    "Included / India": true,
    "Included / International": true,
    "Price / International": "",
    "Compare At Price / International": "",
    Status: "active",
  },
  {
    Handle: "silver-threader-necklace",
    Title: "",
    "Body (HTML)": "",
    Vendor: "",
    "Product Category": "",
    Type: "",
    Tags: "",
    Published: "",
    "Option1 Name": "",
    "Option1 Value": "",
    "Option2 Name": "",
    "Option2 Value": "",
    "Option3 Name": "",
    "Option3 Value": "",
    "Variant SKU": "",
    "Variant Grams": "",
    "Variant Inventory Tracker": "",
    "Variant Inventory Qty": "",
    "Variant Inventory Policy": "",
    "Variant Fulfillment Service": "",
    "Variant Price": "",
    "Variant Compare At Price": "",
    "Variant Requires Shipping": "",
    "Variant Taxable": "",
    "Variant Barcode": "",
    "Image Src":
      "https://cdn.shopify.com/s/files/1/0814/6190/3638/products/threader-necklace-closeup_925x_eb965b96-d5ca-48f5-98db-b2f912d13123.jpg?v=1692687744",
    "Image Position": 2,
    "Image Alt Text": "",
    "Gift Card": "",
    "SEO Title": "",
    "SEO Description": "",
    "Google Shopping / Google Product Category": "",
    "Google Shopping / Gender": "",
    "Google Shopping / Age Group": "",
    "Google Shopping / MPN": "",
    "Google Shopping / Condition": "",
    "Google Shopping / Custom Product": "",
    "Google Shopping / Custom Label 0": "",
    "Google Shopping / Custom Label 1": "",
    "Google Shopping / Custom Label 2": "",
    "Google Shopping / Custom Label 3": "",
    "Google Shopping / Custom Label 4": "",
    "Variant Image": "",
    "Variant Weight Unit": "",
    "Variant Tax Code": "",
    "Cost per item": "",
    "Included / India": "",
    "Included / International": "",
    "Price / International": "",
    "Compare At Price / International": "",
    Status: "",
  },
  {
    Handle: "stylish-summer-neclace",
    Title: "Stylish Summer Necklace",
    "Body (HTML)":
      "<p>Double chained gold boho necklace with turquoise pendant.</p>",
    Vendor: "Company 123",
    "Product Category": "",
    Type: "Necklace",
    Tags: "Gold, Turquoise",
    Published: true,
    "Option1 Name": "Title",
    "Option1 Value": "Default Title",
    "Option2 Name": "",
    "Option2 Value": "",
    "Option3 Name": "",
    "Option3 Value": "",
    "Variant SKU": "",
    "Variant Grams": 0,
    "Variant Inventory Tracker": "",
    "Variant Inventory Qty": 1,
    "Variant Inventory Policy": "deny",
    "Variant Fulfillment Service": "manual",
    "Variant Price": 44.99,
    "Variant Compare At Price": "",
    "Variant Requires Shipping": true,
    "Variant Taxable": true,
    "Variant Barcode": "",
    "Image Src":
      "https://cdn.shopify.com/s/files/1/0814/6190/3638/products/stylish-summer-necklace_925x_1e57a91f-a1d3-4360-9ddb-9d7db86a709f.jpg?v=1692687746",
    "Image Position": 1,
    "Image Alt Text": "",
    "Gift Card": false,
    "SEO Title": "",
    "SEO Description": "",
    "Google Shopping / Google Product Category": "",
    "Google Shopping / Gender": "",
    "Google Shopping / Age Group": "",
    "Google Shopping / MPN": "",
    "Google Shopping / Condition": "",
    "Google Shopping / Custom Product": "",
    "Google Shopping / Custom Label 0": "",
    "Google Shopping / Custom Label 1": "",
    "Google Shopping / Custom Label 2": "",
    "Google Shopping / Custom Label 3": "",
    "Google Shopping / Custom Label 4": "",
    "Variant Image": "",
    "Variant Weight Unit": "kg",
    "Variant Tax Code": "",
    "Cost per item": "",
    "Included / India": true,
    "Included / International": true,
    "Price / International": "",
    "Compare At Price / International": "",
    Status: "active",
  },
];
